### PR TITLE
Export developed-by component

### LINKED ISSUE #43: Please export all built components
I'm trying to use `DevelopedBy` but it's not exported in the module (I can see the component in the repo though).

Using module ver. `0.1.2`

### PR DESCRIPTION
**Pull request by moonflare**
#### What changed?
 - Exports developed-by component

Closes #43

### CODE REVIEW

**Comment by moonflare** [comment]
Please hold reviews. The import/export of `.png files` breaks the build. We need to add https://github.com/rollup/plugins/tree/master/packages/image

**Comment by Utwo** [comment]
> Please hold reviews. The import/export of `.png files` breaks the build. We need to add https://github.com/rollup/plugins/tree/master/packages/image

From image repo: 

> Images are encoded using base64, which means they will be 33% larger than the size on disk. You should therefore only use this for small images where the convenience of having them available on startup (e.g. rendering immediately to a canvas without co-ordinating asynchronous loading of several images) outweighs the cost.

**Comment by moonflare** [comment]
> > Please hold reviews. The import/export of `.png files` breaks the build. We need to add https://github.com/rollup/plugins/tree/master/packages/image
> 
> From image repo:
> 
> > Images are encoded using base64, which means they will be 33% larger than the size on disk. You should therefore only use this for small images where the convenience of having them available on startup (e.g. rendering immediately to a canvas without co-ordinating asynchronous loading of several images) outweighs the cost.

Didn't look too much into it. Will find a fix later tonight. I think we might have SVGs for those logos anyways.

**Comment by moonflare** [comment]
Fixed by #45

**Pull request closed without merging**
