### PR TITLE
Add support for 'partnerLogos' to IncubatedBy component

### PR DESCRIPTION
**Pull request by cipick**
### What changed?
 - Adds support for `partnerLogos` to IncubatedBy component
 - Closes https://github.com/code4romania/taskforce-fe-components/issues/189

### Actions (optional)
 - [x] Increase the version of the package if you need to release it after the merge
 - [ ] If you added a new component, please make sure to export it in `../src/index.js`

### CODE REVIEW

**Comment by Utwo** [comment]
Please update the path version in package.json and compress/resize the image if necessary

**Comment by RaduCStefanescu** [comment]
Hi @cipick can you please update your PR with the comments from @Utwo  so we can merge this issue?
Thank you!

**Comment by cipick** [comment]
@RaduCStefanescu @Utwo @tudoramariei  could you please have another look? image has been compressed with `ImageOptim` and package version bumped up

**Comment by RaduCStefanescu** [comment]
Thank you everyone for your work 🙏

**Pull request merged**
